/**
 * Shared constants for Shorts counter.
 */

const SESSION_STORAGE_KEY = 'ytCommanderShortsCounterSession';
const LABEL_ID = 'shorts-counter-label';

const SAVE_DEBOUNCE_MS = 700;
const OBSERVER_THROTTLE_MS = 260;
const DELTA_LIFETIME_MS = 760;
const BUMP_RESET_MS = 460;
const RESET_FEEDBACK_MS = 380;
const END_BIND_DELAY_MS = 140;
const AUTO_SCROLL_END_THRESHOLD_S = 0.2;
const AUTO_SCROLL_LOOP_RESTART_THRESHOLD_S = 0.35;
const AUTO_SCROLL_LOCK_RELEASE_MS = 1200;

export {
    SESSION_STORAGE_KEY,
    LABEL_ID,
    SAVE_DEBOUNCE_MS,
    OBSERVER_THROTTLE_MS,
    DELTA_LIFETIME_MS,
    BUMP_RESET_MS,
    RESET_FEEDBACK_MS,
    END_BIND_DELAY_MS,
    AUTO_SCROLL_END_THRESHOLD_S,
    AUTO_SCROLL_LOOP_RESTART_THRESHOLD_S,
    AUTO_SCROLL_LOCK_RELEASE_MS
};
